config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/search', to: 'pages#search'

  get 'sessions/create', to: 'sessions#create'
  get 'sessions/destroy', to: 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :provider, presence: true
  validates :uid, presence: true

  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash[:uid], provider: auth_hash[:provider]) do |u|
      u.name = auth_hash[:info][:name]
      u.image_url = auth_hash[:info][:image]
      u.url = auth_hash[:info][:urls][:Github]
    end

    # We always want to update the attributes below
    user.token = auth_hash[:credentials][:token]
    user.location = auth_hash[:extra][:raw_info][:location]
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    unless logged_in?
      flash[:warn] = 'You must first login to view a restricted page'
      redirect_to :root
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :ensure_logged_in, only: :search

  def home
  end

  def search
    if page_params[:search_term]
      pattern = page_params[:search_term].dup
      if page_params[:language_filter].present?
        pattern << " language:#{page_params[:language_filter]}"
        @language_filter = page_params[:language_filter]
      end
      @octo_params = build_octo_params(page_params)
      puts @octo_params
      @results = get_client.search_repositories(pattern, @octo_params )
      @search_term = page_params[:search_term]
    end
  end

  private

  def get_client
    @client ||= Octokit::Client.new(access_token: current_user.token)
  end

  def build_octo_params(page_params)
    {}.tap do |octo|
      octo[:utf8] = page_params[:utf8] if page_params[:utf8].present?
      octo[:commit] = page_params[:commit] if page_params[:commit].present?
      octo[:page] = page_params[:page] if page_params[:page].present?
      octo[:per_page] = 22
      # Sort attributes are stored in the session
      if page_params[:sort_by].present?
        if session[:sort_by] == page_params[:sort_by] # just toggle if on the same column
          session[:sort_order] = session[:sort_order] == 'desc' ? 'asc' : 'desc'
        else # sort numerics 'desc', alphas 'asc'
          session[:sort_by] = page_params[:sort_by]
          session[:sort_order] = 'desc'
        end
      end
      octo[:sort] = session[:sort_by].present? ? session[:sort_by] : 'stars'
      octo[:order] = session[:sort_order].present? ? session[:sort_order] : 'desc'
    end
  end

  def page_params
    params.permit(:search_term, :language_filter, :page, :utf8, :commit, :sort_by)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    begin  # begin is required!
      user = User.from_omniauth(request.env['omniauth.auth'].deep_symbolize_keys)
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.name}!"
      redirect_to :pages_search
    rescue StandardError => e
      flash[:warning] = "There was error trying to authenticate you...#{e}"
      redirect_to :pages_home
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def page_from_href(last_response_rel)
    last_response_rel.href.match(/[&\?]page=(\d+)/)[1].to_i
  end

  def number_of_pages(last_response)
    total_pages = 1
    if last_response.rels[:last].present?
      total_pages = page_from_href(last_response.rels[:last])
    elsif last_response.rels[:prev].present?
      total_pages = page_from_href(last_response.rels[:prev]) + 1
    end
    total_pages
  end

  def get_current_page(last_response)
    current = 1
    if last_response.rels[:next].present?
      current = page_from_href(last_response.rels[:next]) - 1
    elsif last_response.rels[:prev].present?
      current = page_from_href(last_response.rels[:prev]) + 1
    end
    current
  end

  def active_sort?(title, sort_by, sort_order)
    return '' unless sort_by == title
    "sort-#{sort_order}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ghsearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Rubik|Source+Sans+Pro" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="flash-container">
  <% flash.each do |key, val| %>
    <div class="flash-<%= key %>">
      <%= val %>
    </div>
  <% end %>
</div>
<div id="loginator">
  <% if logged_in? %>
    <span class="logged-in"><%= current_user.name %> signed in &nbsp; <%= link_to 'Logout', :sessions_destroy %></span>
  <% else %>
    <span class="logged-out">Please <%= link_to 'login', '/auth/github' %></span>
  <% end %>
</div>

<div class="main-wrapper">
<%= yield %>
</div>

</body>
</html>

app/views/pages/_pagination.html.erb
<div class="pagination"><span class="total-count"><%= total_count %> results</span>
  <% ellipsis_count = 0; ellipsis = false %>
  <% for i in 1..number_of_pages %>
    <% if number_of_pages >= 10 %>
      <% if i > 2 && (current_page - i).abs > 2 && i < number_of_pages - 1 %>
        <% ellipsis_count += 1; ellipsis = true %>
        <% if ellipsis_count > 2 %>
          <% next %>
        <% end %>
      <% else %>
        <% ellipsis = false; ellipsis_count = 0 %>
      <% end %>
    <% end %>
    <span class="page-number<%= i == current_page ? ' current' : '' %>">
        <%= "#{ ellipsis ? '.' : i}" %></span>
  <% end %>
</div>

app/views/pages/_results.html.erb
<table id="results-list">
  <thead><tr><th>Name</th><th>Owner</th>
    <th class="stars-heading sortable"><span class="<%= active_sort?('stars', sort_by, sort_order) %>">Stars</span></th>
    <th class="forks-heading sortable"><span class="<%= active_sort?('forks', sort_by, sort_order) %>">Forks</span></th>
    <th>Language</th>
    <th class="updated-at sortable"
        title="Github is not sorting perfectly here (using pushed_at, since better results)">
      <span class="<%= active_sort?('updated', sort_by, sort_order) %>">Updated</span></th>
    <th>Description</th></tr>
  </thead>
  <% results&.items&.each do |row| %>
    <tr><td><a href="<%= row[:html_url] %>"><%= row[:name] %></a></td><td><%= row[:owner][:login] %></td>
      <td><%= row[:stargazers_count] %></td>
      <td><%= row[:forks_count] %></td>
      <td><%= row[:language] %></td>
      <td><%= Date.parse("#{row[:pushed_at]}").strftime("%F") %></td>
      <td><%= truncate(row[:description], length: 248) %></td>
    </tr>
  <% end %>
</table>

app/views/pages/home.html.erb
<h1>Slick Github Search</h1>
<p>Please <%= link_to 'login', '/auth/github' %> to start searching</p>

<p>This is an awesome search app. You really should login and give it a try!</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus blanditiis dignissimos dolore facere harum ipsa magni optio porro, praesentium, rerum sint tempore unde? Aut fugiat, nisi perspiciatis quia sit tenetur!
</p>

app/views/pages/index.html.erb
<h1>Slick Github Search</h1>
<p>Please Authenticate with a Social network</p>

<ul>
  <li><%= link_to 'Twitter', '/auth/twitter' %></li>
</ul>

app/views/pages/search.html.erb
<h3 class="page-title">Search Github Repositories</h3>

<%
  if @results && @client.last_response.rels.present?
    total_count = @results.total_count
    last_response = @client.last_response
    total_pages = number_of_pages last_response
    current_page = get_current_page last_response
%>
  <%= render partial: 'pagination',
         locals: {total_count: total_count,
                  number_of_pages: total_pages,
                  current_page: current_page}
  %>
<% end %>

<%= form_tag(pages_search_path, method: :get, id: 'filter-controls') do %>
  <%= label_tag 'search_term' %>
  <%= text_field_tag 'search_term', @search_term %>
  <%= hidden_field_tag('page') %>
  <%= hidden_field_tag('sort_by') %>
  <%= label_tag 'language_filter' %>
  <%= text_field_tag 'language_filter', @language_filter %>
  <%= submit_tag 'Search Repos' %>
<% end %>

<%= render partial: 'results',
           locals: {results: @results,
                    sort_by: (@octo_params && @octo_params[:sort] || ''),
                    sort_order: (@octo_params && @octo_params[:order] || '')} %>

<script type="text/javascript">
  <%= render partial: 'pages.js' %>
</script>